#!/usr/bin/env python3
"""Generate the portable MoonBit IANA IPFIX registry snapshot."""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT = ROOT / "registry" / "data" / "ipfix-information-elements-2026-08-13.csv"
OUTPUT = ROOT / "registry" / "iana_snapshot.mbt"
SOURCE_URL = "https://www.iana.org/assignments/ipfix/ipfix-information-elements.csv"
RETRIEVED_ON = "2026-08-13"
EXPECTED_SHA256 = "896357e0296d8541fa4b7e0afd2dce48b52562dcfdf5437ac36cea428ecdc930"

TYPE_VARIANTS = {
    "octetArray": "OctetArray",
    "unsigned8": "Unsigned8",
    "unsigned16": "Unsigned16",
    "unsigned32": "Unsigned32",
    "unsigned64": "Unsigned64",
    "unsigned256": "Unsigned256",
    "signed8": "Signed8",
    "signed16": "Signed16",
    "signed32": "Signed32",
    "signed64": "Signed64",
    "float32": "Float32",
    "float64": "Float64",
    "boolean": "Boolean",
    "macAddress": "MacAddress",
    "string": "String",
    "dateTimeSeconds": "DateTimeSeconds",
    "dateTimeMilliseconds": "DateTimeMilliseconds",
    "dateTimeMicroseconds": "DateTimeMicroseconds",
    "dateTimeNanoseconds": "DateTimeNanoseconds",
    "ipv4Address": "Ipv4Address",
    "ipv6Address": "Ipv6Address",
    "basicList": "BasicList",
    "subTemplateList": "SubTemplateList",
    "subTemplateMultiList": "SubTemplateMultiList",
}

CANONICAL_LENGTHS = {
    "unsigned8": 1,
    "unsigned16": 2,
    "unsigned32": 4,
    "unsigned64": 8,
    "unsigned256": 32,
    "signed8": 1,
    "signed16": 2,
    "signed32": 4,
    "signed64": 8,
    "float32": 4,
    "float64": 8,
    "boolean": 1,
    "macAddress": 6,
    "dateTimeSeconds": 4,
    "dateTimeMilliseconds": 8,
    "dateTimeMicroseconds": 8,
    "dateTimeNanoseconds": 8,
    "ipv4Address": 4,
    "ipv6Address": 16,
}


def moon_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True, separators=(",", ":"))


def moon_option(value: str) -> str:
    return "None" if not value else f"Some({moon_string(value)})"


def read_entries() -> list[dict[str, str]]:
    digest = hashlib.sha256(SNAPSHOT.read_bytes()).hexdigest()
    if digest != EXPECTED_SHA256:
        raise SystemExit(
            f"snapshot digest mismatch: expected {EXPECTED_SHA256}, found {digest}"
        )
    with SNAPSHOT.open("r", encoding="utf-8-sig", newline="") as source:
        rows = list(csv.DictReader(source))
    entries: list[dict[str, str]] = []
    seen: set[int] = set()
    for row in rows:
        raw_id = row["ElementID"].strip()
        data_type = row["Abstract Data Type"].strip()
        if not raw_id.isdigit() or not data_type:
            continue
        element_id = int(raw_id)
        if element_id in seen:
            raise SystemExit(f"duplicate standard ElementID {element_id}")
        if data_type not in TYPE_VARIANTS:
            raise SystemExit(f"unknown abstract data type {data_type!r} for IE {element_id}")
        seen.add(element_id)
        entries.append(
            {
                "id": str(element_id),
                "name": row["Name"].strip(),
                "type": data_type,
                "semantics": row["Data Type Semantics"].strip(),
                "units": row["Units"].strip(),
                "status": row["Status"].strip(),
            }
        )
    entries.sort(key=lambda item: int(item["id"]))
    return entries


def render() -> str:
    entries = read_entries()
    lines = [
        "// Generated by tools/generate_registry.py; do not edit by hand.",
        "",
        "///|",
        f"pub let iana_source_url : String = {moon_string(SOURCE_URL)}",
        "",
        "///|",
        f"pub let iana_retrieved_on : String = {moon_string(RETRIEVED_ON)}",
        "",
        "///|",
        f"pub let iana_sha256 : String = {moon_string(EXPECTED_SHA256)}",
        "",
        "///|",
        f"pub let iana_entry_count : Int = {len(entries)}",
        "",
        "///|",
        "let iana_entries : Array[ElementMetadata] = [",
    ]
    for entry in entries:
        status = entry["status"]
        if status == "current":
            status_expr = "RegistryStatus::Current"
        elif status == "deprecated":
            status_expr = "RegistryStatus::Deprecated"
        else:
            status_expr = f"RegistryStatus::Unknown({moon_string(status)})"
        canonical = CANONICAL_LENGTHS.get(entry["type"])
        canonical_expr = "None" if canonical is None else f"Some({canonical})"
        lines.extend(
            [
                "  {",
                f"    identity: {{ enterprise_number: 0U, element_id: {entry['id']}U }},",
                f"    name: {moon_string(entry['name'])},",
                "    abstract_data_type: "
                f"AbstractDataType::{TYPE_VARIANTS[entry['type']]},",
                f"    semantics: {moon_option(entry['semantics'])},",
                f"    units: {moon_option(entry['units'])},",
                f"    status: {status_expr},",
                f"    canonical_length: {canonical_expr},",
                "  },",
            ]
        )
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="fail if generated output is stale"
    )
    args = parser.parse_args()
    rendered = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit("registry/iana_snapshot.mbt is stale; regenerate it")
        return 0
    OUTPUT.write_text(rendered, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
